# DataSource Config
server:
   port: 9110   
   
spring:
   cloud:
      nacos:
         discovery:
            server-addr: 192.168.26.85:8848
      sentinel:
         transport:
            port: 8819
            dashboard: 127.0.0.1:8868
            #dashboard: 192.168.26.85:8868         
#上传链路数据到zipkin
   zipkin:
      #zipkin控制台地址
      base-url: http://192.168.26.85:9411
   sleuth:
      sampler:
         #采样率[0,1] 1代表全部采样
         probability: 1   
   
dubbo:
   cloud:
      subscribed-services: dubbo-provider-service
   protocol:
      name: dubbo
      port: 21881
   registry:
      address: spring-cloud://192.168.26.85   
   consumer:
      check: false 
      retries: 0    
      filter: tracing
   provider:
      filter: tracing       
          
# Logger Config
logging:
   level:
      org.com.spring.cloud.api: info
    
    
#spring boot actutor监控收集   
management:
   endpoints:
      web:
         exposure:
            include: '*'
            
#要用sentinel来支持feign的fallback功能            
feign:
   sentinel:
      enabled: true            